#!/bin/bash
# minmaxing commit summarizer — auto-summarizes git commits to obsidian
# Called by git post-commit hook
# Usage: commit-summarize.sh [commit_hash]

set -e

COMMIT_HASH="${1:-$(git rev-parse HEAD 2>/dev/null)}"
MEMORY_DIR="${MEMORY_DIR:-$(pwd)/obsidian/Memory}"
TASTE_DIR="${TASTE_DIR:-$(pwd)/.taste}"
COMMIT_DIR="${MEMORY_DIR}/Stories/commits"

# Ensure directories exist
mkdir -p "${COMMIT_DIR}"

# Get commit metadata
if ! git show "$COMMIT_HASH" --quiet &>/dev/null; then
    echo "[commit-summarize] Commit $COMMIT_HASH not found, skipping"
    exit 0
fi

COMMIT_MSG=$(git log -1 --format="%s" "$COMMIT_HASH" 2>/dev/null)
COMMIT_BODY=$(git log -1 --format="%b" "$COMMIT_HASH" 2>/dev/null | head -5)
COMMIT_AUTHOR=$(git log -1 --format="%an" "$COMMIT_HASH" 2>/dev/null)
COMMIT_DATE=$(git log -1 --format="%ad" --date=short "$COMMIT_HASH" 2>/dev/null)
COMMIT_DATETIME=$(git log -1 --format="%ad %at" --date=iso "$COMMIT_HASH" 2>/dev/null)
SHORT_HASH=$(git rev-parse --short "$COMMIT_HASH" 2>/dev/null)
FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r "$COMMIT_HASH" 2>/dev/null | wc -l | tr -d ' ')
FILE_LIST=$(git diff-tree --no-commit-id --name-only -r "$COMMIT_HASH" 2>/dev/null | tr '\n' ',' | sed 's/,$//')

# Determine commit type from message
COMMIT_TYPE="changes"
case "$COMMIT_MSG" in
    feat*) COMMIT_TYPE="feat" ;;
    fix*)  COMMIT_TYPE="fix" ;;
    docs*) COMMIT_TYPE="docs" ;;
    refactor*) COMMIT_TYPE="refactor" ;;
    test*) COMMIT_TYPE="test" ;;
    perf*) COMMIT_TYPE="perf" ;;
    chore*) COMMIT_TYPE="chore" ;;
esac

# Generate filename: commits/YYYY-MM-DD-{short-hash}.md
FILENAME="${COMMIT_DATE}-${SHORT_HASH}.md"
FILEPATH="${COMMIT_DIR}/${FILENAME}"

# Check if already summarized (idempotency)
if [ -f "$FILEPATH" ]; then
    echo "[commit-summarize] Already summarized: ${SHORT_HASH}"
    exit 0
fi

# Generate summary (2-3 sentences max)
SUMMARY="${COMMIT_MSG}"
if [ -n "$COMMIT_BODY" ]; then
    BODY_TRIMMED=$(echo "$COMMIT_BODY" | sed 's/^[[:space:]]*//' | head -c 200)
    if [ -n "$BODY_TRIMMED" ]; then
        SUMMARY="${COMMIT_MSG}. ${BODY_TRIMMED}"
    fi
fi

# Write obsidian note with frontmatter
cat > "$FILEPATH" <<EOF
---
type: commit-summary
date: ${COMMIT_DATE}
commit_hash: ${COMMIT_HASH}
author: ${COMMIT_AUTHOR}
commit_type: ${COMMIT_TYPE}
files_changed: ${FILES_CHANGED}
---

# ${COMMIT_MSG}

${SUMMARY}

## Files Changed
${FILE_LIST}

## Metadata
- **Commit**: ${COMMIT_HASH}
- **Author**: ${COMMIT_AUTHOR}
- **Date**: ${COMMIT_DATE}
- **Files**: ${FILES_CHANGED}

---

*Auto-generated by minmaxing commit-summarize.sh*
EOF

echo "[commit-summarize] Summarized: ${FILENAME}"

# Also write to SQLite for agent retrieval (best-effort)
python3 -c "
import sys
sys.path.insert(0, '$(pwd)')
try:
    from memory.sqlite_db import MemoryDB
    db = MemoryDB()
    db.add_semantic(
        text='${COMMIT_MSG} | ${SUMMARY}',
        category='commit',
        tags=['commit', '${COMMIT_TYPE}', 'git', '${COMMIT_DATE}']
    )
    db.close()
except Exception as e:
    print(f'[commit-summarize] SQLite write skipped: {e}')
" 2>/dev/null || echo "[commit-summarize] SQLite skipped"

exit 0
